export default {
    INI_RECEIVE: 'INI_RECEIVE',
    ITEM_RECEIVE: 'ITEM_RECEIVE',
    ITEM_LOADING: 'ITEM_LOADING',
    
    MESS_INPUT: 'MESS_INPUT',
    MESS_UPDATE: 'MESS_UPDATE',
    MESS_UPDATE_INPUT: 'MESS_UPDATE_INPUT',
    MESS_ADD: 'MESS_ADD',
    MESS_CLEAR: 'MESS_CLEAR',
    MESS_DISPLAY: 'MESS_DISPLAY',

    REDIRECT: 'REDIRECT',
    RSREDIRECT: 'RSREDIRECT',
    DETAIL_VIEW: 'DETAIL_VIEW',
    LOGIN: 'Login'
}
